### ISSUE TITLE
Is django-on-heroku needed these days?

### ISSUE THREAD

**Issue by abulka** [pkrefta/django-on-heroku#7]
Thanks for this project - I’ve got issues where the old `django-heroku` is causing a failed install of psycopg2 even though I already have psycopg2-binary specified and installed. Am about to try out your new fork to see if it fixes things.

The Heroku Django deployment documentation doesn’t mention django-heroku anymore, and has apparently been greatly simplified to just two easy steps in the Heroku docs: https://devcenter.heroku.com/articles/heroku-postgresql#connecting-with-django
So do we still need django-heroku or this updated django-on-heroku?

**Comment by hkennyv** [comment]
It seems like django-on-heroku includes those two lines that you linked as well as configuring some other middleware

**Comment by pkrefta** [comment]
Except for psycopg2 this project also includes configuration for whitenoise for statics serving and few other things so it's little easier to get going smoothly.

Thanks for asking 😃
